version: '3'

volumes:
    chdb_data: {}

services:
  chdb-server-bun:
    image: ghcr.io/metrico/chdb-bun-server:latest
    container_name: chdb-server-bun
    restart: unless-stopped
    expose:
      - 8123
    volumes:
      - chdb_data:/app/.chdb_data
    environment:
      - PORT=8123
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 500M

  qryn:
    image: qxip/qryn:bun
    container_name: qryn-chdb-bun
    restart: unless-stopped
    expose:
      - 3100
    ports:
      - "3300:3100"
    environment:
      - CLICKHOUSE_SERVER=chdb-server-bun
      - CLICKHOUSE_AUTH="qryn:demo"
      - CLICKHOUSE_PORT=8123
      - LOG_LEVEL=debug
      - NODE_OPTIONS="--max-old-space-size=4096"
    depends_on:
       - chdb-server-bun
